version: "3.9"
services:
  backend:
    build: ./backend
    container_name: vanit_backend
    ports:
      - "5000:5000"
  frontend:
    build: ./frontend
    container_name: vanit_frontend
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend